project_id = "link-vault"

[api]
  enabled = true
  port = 54321
  schema = "public,storage,graphql_public"
  extra_search_path = ["public", "extensions"]
  max_rows = 1000

[db]
  port = 54322
  major_version = 15

[studio]
  port = 54323

[inbucket]
  enabled = true
  port = 54324

[analytics]
  enabled = false

[dashboard]
  enabled = true
  port = 54326

[functions]
  port = 54327

[auth]
  site_url = "http://localhost:3000"
  additional_redirect_urls = [
    "http://localhost:3000/auth/callback",
    "http://localhost:3000/auth/confirm",
  ]
  jwt_expiry = 3600
  enable_signup = true
