name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality-checks:
    name: Lint, typecheck, tests
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SUPABASE_URL: http://127.0.0.1:54321
      NEXT_PUBLIC_SUPABASE_ANON_KEY: test-anon-key
      SUPABASE_SERVICE_ROLE_KEY: test-service-role-key
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        uses: microsoft/playwright-github-action@v1

      - name: Run ESLint
        run: pnpm lint

      - name: Typecheck TypeScript
        run: pnpm typecheck

      - name: Run unit and integration tests with coverage
        run: pnpm test --coverage

      - name: Run end-to-end tests
        run: pnpm test:e2e

      - name: Run accessibility tests
        run: pnpm test:a11y

      - name: Lint Supabase schema
        if: env.SUPABASE_DB_URL != ''
        run: pnpm dlx supabase db lint --db-url "$SUPABASE_DB_URL" --fail-on warning

  deploy:
    name: Deploy to Vercel
    needs: quality-checks
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SUPABASE_URL: http://127.0.0.1:54321
      NEXT_PUBLIC_SUPABASE_ANON_KEY: test-anon-key
      SUPABASE_SERVICE_ROLE_KEY: test-service-role-key
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Apply Supabase migrations
        if: env.SUPABASE_DB_URL != ''
        run: pnpm dlx supabase db push --db-url "$SUPABASE_DB_URL"

      - name: Pull Vercel environment
        if: env.VERCEL_TOKEN != '' && env.VERCEL_ORG_ID != '' && env.VERCEL_PROJECT_ID != ''
        run: |
          pnpm dlx vercel pull --yes --environment=production --token "$VERCEL_TOKEN" --project "$VERCEL_PROJECT_ID" --scope "$VERCEL_ORG_ID"

      - name: Build with Vercel
        if: env.VERCEL_TOKEN != '' && env.VERCEL_ORG_ID != '' && env.VERCEL_PROJECT_ID != ''
        run: pnpm dlx vercel build --prod --token "$VERCEL_TOKEN"

      - name: Deploy to production
        if: env.VERCEL_TOKEN != '' && env.VERCEL_ORG_ID != '' && env.VERCEL_PROJECT_ID != ''
        run: pnpm dlx vercel deploy --prebuilt --prod --token "$VERCEL_TOKEN"
